#!/usr/bin/env bash
set -u
set -o pipefail
shopt -s nullglob

SECKIT_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LOG_DIR="$SECKIT_ROOT/.bootstrap-logs"
BUILD_BIN_DIR="$SECKIT_ROOT/.bootstrap-build/bin"
BIN_DIR="${SECKIT_BIN_DIR:-$HOME/bin}"
PIP_USER_BIN="$HOME/.local/bin"

declare -a INSTALLED=()
declare -a FAILED=()
declare -a SKIPPED=()
declare -A REQUIREMENTS_DONE=()

APT_UPDATED=0

log() {
    printf '[*] %s\n' "$*"
}

ok() {
    printf '[+] %s\n' "$*"
}

warn() {
    printf '[!] %s\n' "$*"
}

err() {
    printf '[-] %s\n' "$*" >&2
}

record_status() {
    local bucket="$1"
    local label="$2"
    local detail="${3:-}"
    local line="$label"

    if [ -n "$detail" ]; then
        line="$label - $detail"
    fi

    case "$bucket" in
        installed) INSTALLED+=("$line") ;;
        failed) FAILED+=("$line") ;;
        skipped) SKIPPED+=("$line") ;;
    esac
}

slugify() {
    printf '%s' "$1" | tr ' /' '__' | tr -cd '[:alnum:]_.-'
}

run_as_root() {
    if [ "$(id -u)" -eq 0 ]; then
        "$@"
    elif command -v sudo >/dev/null 2>&1; then
        sudo "$@"
    else
        return 127
    fi
}

run_logged() {
    local label="$1"
    shift

    local logfile="$LOG_DIR/$(slugify "$label").log"
    if "$@" >"$logfile" 2>&1; then
        ok "$label"
        return 0
    fi

    err "$label failed (log: $logfile)"
    tail -n 20 "$logfile" >&2 || true
    return 1
}

ensure_dirs() {
    mkdir -p "$LOG_DIR" "$BUILD_BIN_DIR" "$BIN_DIR"
}

ensure_bin_path_notice() {
    case ":$PATH:" in
        *":$BIN_DIR:"*) ;;
        *)
            warn "$BIN_DIR is not on PATH for this shell. Add it to your shell profile if needed."
            record_status skipped "PATH" "add $BIN_DIR to PATH for launcher shortcuts"
            ;;
    esac
}

safe_symlink() {
    local label="$1"
    local source_path="$2"
    local target_path="$3"

    if [ ! -e "$source_path" ]; then
        record_status failed "$label" "source missing: $source_path"
        return 1
    fi

    if [ -L "$target_path" ]; then
        if [ "$(readlink -f "$target_path")" = "$(readlink -f "$source_path")" ]; then
            record_status skipped "$label" "launcher already points at $source_path"
            return 0
        fi

        warn "Keeping existing symlink: $target_path"
        record_status skipped "$label" "existing symlink preserved at $target_path"
        return 0
    fi

    if [ -e "$target_path" ]; then
        warn "Keeping existing file: $target_path"
        record_status skipped "$label" "existing file preserved at $target_path"
        return 0
    fi

    ln -s "$source_path" "$target_path"
    record_status installed "$label" "linked $target_path"
}

safe_wrapper() {
    local label="$1"
    local wrapper_name="$2"
    local interpreter="$3"
    local target_path="$4"
    local wrapper_path="$BIN_DIR/$wrapper_name"
    local tmp_path="$wrapper_path.tmp"

    if [ ! -e "$target_path" ]; then
        record_status failed "$label" "entrypoint missing: $target_path"
        return 1
    fi

    if [ -e "$wrapper_path" ] && [ ! -L "$wrapper_path" ] && ! grep -q "Generated by SecKit bootstrap" "$wrapper_path" 2>/dev/null; then
        warn "Keeping user-managed launcher: $wrapper_path"
        record_status skipped "$label" "existing launcher preserved at $wrapper_path"
        return 0
    fi

    cat >"$tmp_path" <<EOF
#!/usr/bin/env bash
# Generated by SecKit bootstrap.
exec $interpreter "$target_path" "\$@"
EOF
    chmod +x "$tmp_path"
    mv "$tmp_path" "$wrapper_path"
    record_status installed "$label" "wrapper created at $wrapper_path"
}

ensure_apt_index() {
    if [ "$APT_UPDATED" -eq 1 ]; then
        return 0
    fi

    if ! command -v apt-get >/dev/null 2>&1; then
        warn "apt-get not found, skipping package installation."
        record_status skipped "apt" "apt-get unavailable on this host"
        return 1
    fi

    if run_logged "apt update" run_as_root apt-get update; then
        APT_UPDATED=1
        return 0
    fi

    record_status failed "apt" "unable to refresh package index"
    return 1
}

install_apt_packages() {
    local package

    if ! ensure_apt_index; then
        return 0
    fi

    for package in "$@"; do
        if dpkg -s "$package" >/dev/null 2>&1; then
            record_status skipped "apt:$package" "already installed"
            continue
        fi

        if run_logged "apt install $package" run_as_root apt-get install -y "$package"; then
            record_status installed "apt:$package" "package installed"
        else
            record_status failed "apt:$package" "package install failed"
        fi
    done
}

install_pip_package() {
    local package="$1"

    if ! command -v python3 >/dev/null 2>&1; then
        record_status failed "pip:$package" "python3 not available"
        return 1
    fi

    if python3 -m pip show "$package" >/dev/null 2>&1; then
        record_status skipped "pip:$package" "already installed"
        return 0
    fi

    if run_logged "pip install $package" python3 -m pip install --user --upgrade "$package"; then
        record_status installed "pip:$package" "package installed"
        return 0
    fi

    record_status failed "pip:$package" "package install failed"
    return 1
}

install_repo_requirements() {
    local label="$1"
    local repo_path="$2"
    shift 2

    local requirements_file
    for requirements_file in "$@"; do
        if [ -f "$repo_path/$requirements_file" ]; then
            if [ -n "${REQUIREMENTS_DONE["$repo_path/$requirements_file"]:-}" ]; then
                return 0
            fi

            if run_logged "pip requirements $label" python3 -m pip install --user --upgrade -r "$repo_path/$requirements_file"; then
                REQUIREMENTS_DONE["$repo_path/$requirements_file"]=1
                record_status installed "$label dependencies" "installed from $requirements_file"
                return 0
            fi

            record_status failed "$label dependencies" "failed to install $requirements_file"
            return 1
        fi
    done

    record_status skipped "$label dependencies" "no requirements file found"
    return 0
}

install_go_tool() {
    local label="$1"
    local repo_path="$2"
    local binary_name="$3"
    shift 3

    local binary_path="$BUILD_BIN_DIR/$binary_name"
    local package_target

    if [ -x "$binary_path" ]; then
        safe_symlink "$label" "$binary_path" "$BIN_DIR/$binary_name"
        return 0
    fi

    if ! command -v go >/dev/null 2>&1; then
        record_status failed "$label" "go compiler not available"
        return 1
    fi

    if [ ! -d "$repo_path" ]; then
        record_status failed "$label" "repo missing at $repo_path"
        return 1
    fi

    for package_target in "$@"; do
        if run_logged "go build $label ($package_target)" bash -lc "cd '$repo_path' && GO111MODULE=on go build -o '$binary_path' '$package_target'"; then
            safe_symlink "$label" "$binary_path" "$BIN_DIR/$binary_name"
            return 0
        fi
    done

    record_status failed "$label" "unable to build from $repo_path"
    return 1
}

install_go_remote_tool() {
    local label="$1"
    local binary_name="$2"
    local package_ref="$3"
    local binary_path="$BUILD_BIN_DIR/$binary_name"

    if [ -x "$binary_path" ]; then
        safe_symlink "$label" "$binary_path" "$BIN_DIR/$binary_name"
        return 0
    fi

    if ! command -v go >/dev/null 2>&1; then
        record_status failed "$label" "go compiler not available"
        return 1
    fi

    if run_logged "go install $label" env GOBIN="$BUILD_BIN_DIR" go install "$package_ref"; then
        safe_symlink "$label" "$binary_path" "$BIN_DIR/$binary_name"
        return 0
    fi

    record_status failed "$label" "go install failed"
    return 1
}

install_python_script_tool() {
    local label="$1"
    local launcher_name="$2"
    local repo_path="$3"
    local script_relpath="$4"
    shift 4

    if [ ! -f "$repo_path/$script_relpath" ]; then
        record_status failed "$label" "entrypoint missing: $repo_path/$script_relpath"
        return 1
    fi

    install_repo_requirements "$label" "$repo_path" "$@" || true
    safe_wrapper "$label" "$launcher_name" "python3" "$repo_path/$script_relpath"
}

install_ruby_script_tool() {
    local label="$1"
    local launcher_name="$2"
    local repo_path="$3"
    local script_relpath="$4"

    if [ ! -f "$repo_path/$script_relpath" ]; then
        record_status failed "$label" "entrypoint missing: $repo_path/$script_relpath"
        return 1
    fi

    safe_wrapper "$label" "$launcher_name" "ruby" "$repo_path/$script_relpath"
}

install_python_package_tool() {
    local label="$1"
    local repo_path="$2"
    local entrypoints_csv="$3"
    local entrypoint
    local linked=0

    if [ ! -d "$repo_path" ]; then
        record_status failed "$label" "repo missing at $repo_path"
        return 1
    fi

    if ! command -v python3 >/dev/null 2>&1; then
        record_status failed "$label" "python3 not available"
        return 1
    fi

    if run_logged "pip install $label" python3 -m pip install --user --upgrade "$repo_path"; then
        record_status installed "$label" "package installed from local repo"
    else
        record_status failed "$label" "pip install from local repo failed"
        return 1
    fi

    IFS=',' read -r -a entrypoints <<< "$entrypoints_csv"
    for entrypoint in "${entrypoints[@]}"; do
        if [ -x "$PIP_USER_BIN/$entrypoint" ]; then
            safe_symlink "$entrypoint" "$PIP_USER_BIN/$entrypoint" "$BIN_DIR/$entrypoint"
            linked=1
        fi
    done

    if [ "$linked" -eq 0 ]; then
        record_status skipped "$label launchers" "entrypoints were not generated in $PIP_USER_BIN"
    fi
}

mark_repo_available() {
    local label="$1"
    local repo_path="$2"
    local note="$3"

    if [ -d "$repo_path" ]; then
        record_status installed "$label" "$note"
    else
        record_status failed "$label" "repo missing at $repo_path"
    fi
}

sync_submodules() {
    if run_logged "git submodule sync" git -C "$SECKIT_ROOT" submodule sync --recursive; then
        record_status installed "submodules" "sync complete"
    else
        record_status failed "submodules" "sync failed"
    fi

    if run_logged "git submodule update" git -C "$SECKIT_ROOT" submodule update --init --recursive; then
        record_status installed "submodule checkout" "all registered modules initialized"
    else
        record_status failed "submodule checkout" "git submodule update failed"
    fi
}

install_core_packages() {
    install_apt_packages \
        git curl wget jq unzip zip tar ca-certificates build-essential pkg-config \
        python3 python3-pip python3-venv python3-dev gcc g++ make \
        ruby ruby-dev golang-go cargo nmap masscan net-tools dnsutils whois \
        tcpdump tshark wireshark-common binwalk exiftool steghide foremost \
        hashcat john yara ripgrep libpcap-dev libssl-dev libffi-dev \
        libxml2-dev libxslt1-dev zlib1g-dev libjpeg-dev

    install_pip_package hashid
    install_pip_package stegoveritas
}

install_tool_launchers() {
    local root="$SECKIT_ROOT"

    install_go_tool "subfinder" "$root/tools/recon/subfinder" subfinder ./v2/cmd/subfinder .
    install_go_tool "amass" "$root/tools/recon/amass" amass ./cmd/amass .
    install_go_tool "httpx" "$root/tools/recon/httpx" httpx ./cmd/httpx .
    install_go_tool "nuclei" "$root/tools/recon/nuclei" nuclei ./cmd/nuclei .
    install_go_tool "naabu" "$root/tools/recon/naabu" naabu ./cmd/naabu .
    install_go_tool "gau" "$root/tools/recon/gau" gau .
    install_go_tool "ffuf" "$root/tools/web/ffuf" ffuf .
    install_go_tool "bettercap" "$root/tools/post/bettercap" bettercap ./cmd/bettercap .
    install_go_remote_tool "dnsx" dnsx github.com/projectdiscovery/dnsx/cmd/dnsx@latest

    install_python_package_tool "GraphQLmap" "$root/tools/web/GraphQLmap" "graphqlmap"
    install_python_script_tool "sqlmap" sqlmap "$root/tools/web/sqlmap" sqlmap.py
    install_python_script_tool "XSStrike" xsstrike "$root/tools/web/XSStrike" xsstrike.py requirements.txt
    install_python_script_tool "SSRFmap" ssrfmap "$root/tools/web/SSRFmap" ssrfmap.py requirements.txt
    install_python_script_tool "jwt_tool" jwt-tool "$root/tools/web/jwt_tool" jwt_tool.py requirements.txt
    install_ruby_script_tool "XXEinjector" xxeinjector "$root/tools/web/XXEinjector" XXEinjector.rb
    install_python_script_tool "AutoRecon" autorecon "$root/tools/exploitation/AutoRecon" autorecon.py requirements.txt
    install_python_script_tool "Volatility3" vol "$root/tools/forensics/volatility3" vol.py requirements-minimal.txt requirements.txt
    install_python_script_tool "Loki" loki "$root/tools/forensics/loki" loki.py requirements.txt
    install_python_script_tool "ScoutSuite" scoutsuite "$root/tools/cloud/ScoutSuite" ScoutSuite.py requirements.txt

    install_python_package_tool "plaso" "$root/tools/forensics/plaso" "log2timeline.py,psort.py"
    install_python_package_tool "pwntools" "$root/tools/crypto/pwntools" "pwn"
    install_python_package_tool "impacket" "$root/tools/cross/impacket" "GetNPUsers.py,GetUserSPNs.py,lookupsid.py,ntlmrelayx.py,psexec.py,secretsdump.py,smbclient.py,wmiexec.py"
    install_python_package_tool "pacu" "$root/tools/cloud/pacu" "pacu"
    install_python_package_tool "prowler" "$root/tools/cloud/prowler" "prowler"

    if [ -f "$root/tools/post/PEASS-ng/linPEAS/linpeas.sh" ]; then
        safe_symlink "linpeas" "$root/tools/post/PEASS-ng/linPEAS/linpeas.sh" "$BIN_DIR/linpeas"
    else
        record_status skipped "linpeas" "PEASS-ng submodule not initialized yet"
    fi

    if [ -f "$root/tools/exploitation/exploitdb/searchsploit" ]; then
        safe_symlink "searchsploit" "$root/tools/exploitation/exploitdb/searchsploit" "$BIN_DIR/searchsploit"
    else
        record_status skipped "searchsploit" "exploitdb checkout missing searchsploit"
    fi

    mark_repo_available "PowerSploit" "$root/tools/post/PowerSploit" "PowerShell toolkit repo available"
    mark_repo_available "mimikatz" "$root/tools/post/mimikatz" "source repo available for Windows builds"
    mark_repo_available "sigma" "$root/tools/forensics/sigma" "rules repo available"
    mark_repo_available "static-binaries" "$root/tools/cross/static-binaries" "portable binary collection available"
}

link_repo_scripts() {
    local script_path
    local launcher_name

    for script_path in "$SECKIT_ROOT"/scripts/*/*.sh; do
        if [ "$(basename "$(dirname "$script_path")")" = "lib" ]; then
            continue
        fi
        launcher_name="$(basename "$script_path" .sh)"
        safe_symlink "$launcher_name" "$script_path" "$BIN_DIR/$launcher_name"
    done
}

update_nuclei_templates() {
    if [ -x "$BIN_DIR/nuclei" ]; then
        if run_logged "nuclei template update" "$BIN_DIR/nuclei" -update-templates; then
            record_status installed "nuclei templates" "template cache refreshed"
        else
            record_status failed "nuclei templates" "template update failed"
        fi
    else
        record_status skipped "nuclei templates" "nuclei launcher unavailable"
    fi
}

print_manual_steps() {
    printf '\n[manual] Still user-managed by design:\n'
    printf '  - tools/windows/* GUI bundles remain manual downloads unless you add your own fetch automation.\n'
    printf '  - If a launcher was skipped because a file already existed in %s, the bootstrap intentionally left it alone.\n' "$BIN_DIR"
}

print_summary() {
    local line

    printf '\n==== SecKit Bootstrap Summary ====\n'

    printf '\nInstalled / updated:\n'
    if [ "${#INSTALLED[@]}" -eq 0 ]; then
        printf '  - none\n'
    else
        for line in "${INSTALLED[@]}"; do
            printf '  - %s\n' "$line"
        done
    fi

    printf '\nSkipped / preserved:\n'
    if [ "${#SKIPPED[@]}" -eq 0 ]; then
        printf '  - none\n'
    else
        for line in "${SKIPPED[@]}"; do
            printf '  - %s\n' "$line"
        done
    fi

    printf '\nFailed:\n'
    if [ "${#FAILED[@]}" -eq 0 ]; then
        printf '  - none\n'
    else
        for line in "${FAILED[@]}"; do
            printf '  - %s\n' "$line"
        done
    fi

    print_manual_steps
}

main() {
    log "SecKit bootstrap starting from $SECKIT_ROOT"
    ensure_dirs
    ensure_bin_path_notice

    sync_submodules
    install_core_packages
    install_tool_launchers
    link_repo_scripts
    update_nuclei_templates
    print_summary
}

main "$@"
